version: "3.8"

services:
  api:
    command: python manage.py runserver 0.0.0.0:${API_PORT}
    volumes:
      - .:/usr/src/app
    ports:
      - "${API_PORT}:${API_PORT}"
    stdin_open: true
    tty: true
  db:
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
