version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"

  api:
    build: .
    image: finances_service:1.0
    command: python manage.py runserver 0.0.0.0:${API_PORT}
    volumes:
      - .:/usr/src/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - ./.env
    stdin_open: true
    tty: true

volumes:
  postgres_data:
