version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

  api:
    build: .
    image: finances_service:1.0
    command: python manage.py runserver 0.0.0.0:${API_PORT}
    volumes:
      - .:/usr/src/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      DJANGO_DB_NAME: ${DB_NAME}
      DJANGO_DB_USER: ${DB_USER}
      DJANGO_DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_DB_HOST: ${DB_HOST}
      DJANGO_DB_PORT: ${DB_PORT}
      PYTHON_ENV: ${PYTHON_ENV}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      RATE_LIMITING: ${RATE_LIMITING}
    stdin_open: true
    tty: true

volumes:
  postgres_data:
